volumes:
  ollama_storage:
  open-webui:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - 3000:8080
    volumes:
      - ollama_storage:/root/.ollama
      - open-webui:/app/backend/data
    extra_hosts:
        - "host.docker.internal:host-gateway"
    network_mode: "host"
    environment:
      - "host.docker.internal:host-gateway"
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_open-webui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --run-once open-webui
    restart: "no"
